<?php defined('BASEPATH') or exit('No direct script access allowed');

$config['module']['leave']['visible']         = true;
$config['module']['leave']['main_warehouse']   = FALSE;
$config['module']['leave']['parent']      = 'leave';
$config['module']['leave']['label']       = 'Leave';
$config['module']['leave']['name']        = 'leave';
$config['module']['leave']['route']       = 'leave';
$config['module']['leave']['view']        = config_item('module_path') .'leave/';
$config['module']['leave']['language']    = 'item_group_lang';
$config['module']['leave']['helper']      = 'leave_helper';
$config['module']['leave']['table']       = 'tb_leave_request';
$config['module']['leave']['model']       = 'Leave_Model';
$config['module']['leave']['permission']  = array(
    'index'   => 'ADMIN DEPARTMENT,ADMIN JKT,ADMIN LUAR JKT,REIMBURSEMENT,PIC STAFF JKT,SUPERVISOR,PROCUREMENT,PROCUREMENT MANAGER,PIC STAFF,ADMIN,SUPER ADMIN,HR MANAGER,HEAD OF SCHOOL,FINANCE MANAGER,VP FINANCE,CHIEF OF FINANCE,CHIEF OPERATION OFFICER',
    'index_approval'   => 'SUPER ADMIN,HR MANAGER,HEAD OF SCHOOL,VP FINANCE,CHIEF OF FINANCE,CHIEF OPERATION OFFICER',
    'create'  => 'ADMIN DEPARTMENT,ADMIN JKT,ADMIN LUAR JKT,REIMBURSEMENT,PIC STAFF JKT,HR MANAGER,HR STAFF,SUPERVISOR,PROCUREMENT,PROCUREMENT MANAGER,PIC STAFF,ADMIN,SUPER ADMIN,HEAD OF SCHOOL,VP FINANCE,CHIEF OF FINANCE,CHIEF OPERATION OFFICER',
    'import'  => 'ADMIN,SUPER ADMIN,VP FINANCE',
    'print'   => 'ADMIN DEPARTMENT,ADMIN JKT,ADMIN LUAR JKT,REIMBURSEMENT,PIC STAFF JKT,SUPERVISOR,PROCUREMENT,PROCUREMENT MANAGER,PIC STAFF,ADMIN,SUPER ADMIN,FINANCE MANAGER,VP FINANCE,CHIEF OF FINANCE,CHIEF OPERATION OFFICER',
    'info'    => 'ADMIN DEPARTMENT,ADMIN JKT,ADMIN LUAR JKT,REIMBURSEMENT,PIC STAFF JKT,SUPERVISOR,PROCUREMENT,PROCUREMENT MANAGER,PIC STAFF,ADMIN,SUPER ADMIN,HR MANAGER,HEAD OF SCHOOL,FINANCE MANAGER,VP FINANCE,CHIEF OF FINANCE,CHIEF OPERATION OFFICER',
    'save'    => 'ADMIN DEPARTMENT,ADMIN JKT,ADMIN LUAR JKT,REIMBURSEMENT,PIC STAFF JKT,HR MANAGER,HR STAFF,SUPERVISOR,PROCUREMENT,PROCUREMENT MANAGER,PIC STAFF,ADMIN,SUPER ADMIN,HEAD OF SCHOOL,VP FINANCE,CHIEF OF FINANCE,CHIEF OPERATION OFFICER',
    'delete'  => 'PROCUREMENT,PROCUREMENT MANAGER,ADMIN,SUPER ADMIN,HEAD OF SCHOOL,VP FINANCE,CHIEF OF FINANCE,CHIEF OPERATION OFFICER',
    'approval'  => 'PROCUREMENT,PROCUREMENT MANAGER,SUPER ADMIN,HR MANAGER,FINANCE MANAGER,CHIEF OF FINANCE,CHIEF OPERATION OFFICER',
);
